---
- hosts: raspberry-pi
  roles:
    - raspberry-pi-apt-packages
- hosts: ie-machines
  roles:
    - ie-machines-apt-packages
    - vnc
    - virtualbox
    - modernie_selenium
- hosts: ff-gc-machine
  roles:
    - ff-gc-machine-apt-packages
    - vnc
