---
- hosts: raspberry-pi
  roles:
    - raspberry-pi-apt-packages
    - selenium-standalone-server
- hosts: ie-machines
  roles:
    - ie-machines-apt-packages
    #- vnc
    #- virtualbox
    #- modernie_selenium
