---
- name: Set timezone variables
  copy: content='GMT' dest=/etc/timezone backup=yes
  notify: update tzdata

- name: update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
  when: ansible_date_time.tz != 'GMT'

- name: Update apt cache
  apt:
    update_cache=yes
    cache_valid_time=3600

#- name: Update all packages to the latest version
#  apt:
#    upgrade=dist

- name: Install required packages
  apt:
    name={{ item }}
    state=present
  with_items:
    - python-pycurl
    - git
    - zip
    - bsd-mailx
