---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

#- name: Update all packages to the latest version
#  apt: upgrade=dist

- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - python-pycurl
    - git
    - zip
    - bsd-mailx
