---
- name: Set timezone variables
  copy: content='Europe/London\n' dest=/etc/timezone backup=yes
  notify: update tzdata

- name: update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

- name: Install add-apt-repostory
  apt:
    name=software-properties-common state=present

- name: Add the Ubuntu Mozilla Security repository
  apt_repository:
    repo='ppa:ubuntu-mozilla-security/ppa'
    state=present

#- name: Add the Google signing key for linux
#  apt_key:
#    url=https://dl-ssl.google.com/linux/linux_signing_key.pub
#    state=present

#- name: Add the Google chrome deb repository
#  apt_repository:
#    repo='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
#    state=present

- name: Add the Webupd8 Oracle Java repository
  apt_repository:
    repo='ppa:webupd8team/java'

- name: Accept the Java 8 license
  debconf:
    name='oracle-java8-installer'
    question='shared/accepted-oracle-license-v1-1'
    value='true'
    vtype='select'

- name: Update apt cache
  apt:
    update_cache=yes
    cache_valid_time=3600

#- name: Update all packages to latest version
#  apt:
#    upgrade=dist

- name: Install apt packages
  apt:
    name={{ item }}
    state=present
  with_items:
    - firefox=47.0.1+build1-0ubuntu0.14.04.1
    #- google-chrome-stable
    - chromium-browser=51.0.2704.79-0ubuntu0.14.04.1.1121
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Get selenium-server-standalone-2.53.1.jar
  get_url:
    url=http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
    dest=~/
  become: True
  become_user: storystream

- name: Get chromedriver_linux32.zip 2.22
  get_url:
    url=http://chromedriver.storage.googleapis.com/2.22/chromedriver_linux32.zip
    dest=~/
  become: True
  become_user: storystream

- name: Check if chromedriver exists
  vars:
    - chromedriver_path: '/home/storystream/chromedriver'
  stat: path={{ chromedriver_path }}
  register: chromedriver

- name: Unzip chromedriver_linux32 2.22
  command:
    unzip -o /home/storystream/chromedriver_linux32.zip -d /home/storystream/
  become: True
  become_user: storystream
  when: chromedriver.stat.exists == False

- name: Add cronjob to bring up Selenium node on startup
  cron:
    special_time=reboot
    name='Run Java command for Selenum host on startup'
    user='storystream'
    job='sudo -u storystream java -jar selenium-server-standalone-2.53.1.jar -role node -nodeConfig /home/storystream/config.json -Dwebdriver.chrome.driver=/home/storystream/chromedriver'
  become: True
  become_user: storystream
