---
- name: Ensure the Webupd8 repository key is present
  apt_key:
    id=0xC2518248EEA14886
    keyserver=keyserver.ubuntu.com
    state=present
  sudo: yes
- name: Ensure the Webupd8 apt repository is present
  apt_repository:
    repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main'
    update_cache=yes
    state=present
  sudo: yes
- name: Ensure the Webupd8 source apt repository is present
  apt_repository:
    repo='deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main'
    update_cache=yes
    state=present
  sudo: yes
- name: Accept the Java 8 license
  sudo: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
- name: Install Oracle Java 8
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
