---
- name: get modernie_selenium from Github
  git:
    repo=https://github.com/abjarnason/modernie_selenium.git
    dest=~/modernie_selenium
  become: True
  become_user: storystream

- name: get selenium-server-standalone-2.53.1.jar
  get_url:
    url=http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
    dest=~/modernie_selenium/Tools/selenium_conf
  become: True
  become_user: storystream

- name: get IEDriverServer_Win32_2.53.1.zip
  get_url:
    url=http://selenium-release.storage.googleapis.com/2.53/IEDriverServer_Win32_2.53.1.zip
    dest=~/modernie_selenium/Tools/selenium_conf/
  become: True
  become_user: storystream

- name: Check if IEDriverServer.exe exists
  vars:
    - ie_driver_path: '/home/storystream/modernie_selenium/Tools/selenium_conf/IEDriverServer.exe'
  stat: path={{ ie_driver_path }}
  register: ie_driver

- name: unzip IEDriverServer_Win32_2.53.1.zip
  command:
    unzip -o /home/storystream/modernie_selenium/Tools/selenium_conf/IEDriverServer_Win32_2.53.1.zip -d ~/modernie_selenium/Tools/selenium_conf/
  #unarchive:
  #  src=~/IEDriverServer_Win32_2.53.1.zip
  #  dest=~/modernie_selenium/Tools/selenium_conf/
  become: True
  become_user: storystream
  when: ie_driver.stat.exists == False

- name: get deuac.iso
  get_url:
    url=https://github.com/tka/SeleniumBox/raw/master/deuac.iso
    dest=~/modernie_selenium/Tools/
  become: True
  become_user: storystream

- name: get jre-8u65-windows-i586.exe
  get_url:
    url=http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jre-8u65-windows-i586.exe
    dest=~/modernie_selenium/Tools/
    headers='Cookie:oraclelicense=accept-securebackup-cookie'
  become: True
  become_user: storystream

- name: Check if IE8 zip exists
  vars:
    - ie8_zip_path: '/home/storystream/modernie_selenium/VMs/IE8.Win7.For.Windows.VirtualBox.zip'
  stat: path={{ ie8_zip_path }}
  register: ie8_zip
  when: ie_version == 'ie8'

- name: Check if IE8 ova exists
  vars:
    - ie8_ova_path: '/home/storystream/modernie_selenium/VMs/IE8 - Win7.ova'
  stat: path={{ ie8_ova_path }}
  register: ie8_ova
  when: ie_version == 'ie8'

- name: get IE8.Win7.For.Windows.VirtualBox.zip
  get_url:
    url=https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/IE8/Windows/IE8.Win7.For.Windows.VirtualBox.zip
    dest=~/modernie_selenium/VMs/
  when: ie_version == 'ie8' and ie8_zip.stat.exists == False
  become: True
  become_user: storystream

- name: unzip IE8.Win7.For.Windows.VirtualBox.zip
  command: unzip -o /home/storystream/modernie_selenium/VMs/IE8.Win7.For.Windows.VirtualBox.zip -d /home/storystream/modernie_selenium/VMs/
  when: ie_version == 'ie8' and ie8_ova.stat.exists == False
  become: True
  become_user: storystream

- name: Check if IE9 zip exists
  var:
    - ie9_zip_path: '/home/storystream/modernie_selenium/VMs/IE9.Win7.For.Windows.VirtualBox.zip'
  stat: path={{ ie9_zip_path }}
  register: ie9_zip
  when: ie_version == 'ie9'

- name: Check if IE9 ova exists
  vars:
    - ie9_ova_path: '/home/storystream/modernie_selenium/VMs/IE9 - Win7.ova'
  stat: path={{ ie9_ova_path }}
  register: ie9_ova
  when: ie_version == 'ie9'

- name: get IE9.Win7.For.Windows.VirtualBox.zip
  get_url:
    url=https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/IE9/Windows/IE9.Win7.For.Windows.VirtualBox.zip
    dest=~/modernie_selenium/VMs/
  when: ie_version == 'ie9' and ie9_zip.stat.exists == False
  become: True
  become_user: storystream

- name: unzip IE9.Win7.For.Windows.VirtualBox.zip
  command: unzip -o /home/storystream/modernie_selenium/VMs/IE9.Win7.For.Windows.VirtualBox.zip -d /home/storystream/modernie_selenium/VMs/
  when: ie_version == 'ie9' and ie9_ova.stat.exists == False
  become: True
  become_user: storystream

- name: Check if IE10 zip exists
  var:
    - ie10_zip_path: '/home/storystream/modernie_selenium/VMs/IE10.Win7.For.Windows.VirtualBox.zip'
  stat: path={{ ie10_zip_path }}
  register: ie10_zip
  when: ie_version == 'ie10'

- name: Check if IE1_exists0 ova exists
  vars:
    - ie10_ova_path: '/home/storystream/modernie_selenium/VMs/IE10 - Win7.ova'
  stat: path={{ ie10_ova_path }}
  register: ie10_ova
  when: ie_version == 'ie10'

- name: get IE10.Win7.For.Windows.VirtualBox.zip
  get_url:
    url=https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/IE10/Windows/IE10.Win7.For.Windows.VirtualBox.zip
    dest=~/modernie_selenium/VMs/
  when: ie_version == 'ie10' and ie10_zip.stat.exists == False
  become: True
  become_user: storystream

- name: unzip IE10.Win7.For.Windows.VirtualBox.zip
  command: unzip -o /home/storystream/modernie_selenium/VMs/IE10.Win7.For.Windows.VirtualBox.zip -d /home/storystream/modernie_selenium/VMs/
  when: ie_version == 'ie10' and ie10_ova.stat.exists == False
  become: True
  become_user: storystream

- name: Check if IE11 zip exists
  var:
    - ie11_zip_path: '/home/storystream/modernie_selenium/VMs/IE11.Win7.For.Windows.VirtualBox.zip'
  stat: path={{ ie11_zip_path }}
  register: ie11_zip
  when: ie_version == 'ie11'

- name: Check if IE11 ova exists
  vars:
    - ie11_ova_path: '/home/storystream/modernie_selenium/VMs/IE11\ -\ Win7.ova'
  stat: path={{ ie11_ova_path }}
  register: ie11_ova
  when: ie_version == 'ie11'

- name: get IE11.Win7.For.Windows.VirtualBox.zip
  get_url:
    url=https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/IE11/Windows/IE11.Win7.For.Windows.VirtualBox.zip
    dest=~/modernie_selenium/VMs/
  when: ie_version == 'ie11' and ie11_zip.stat.exists == False
  become: True
  become_user: storystream

- name: unzip IE11.Win7.For.Windows.VirtualBox.zip
  command: unzip -o /home/storystream/modernie_selenium/VMs/IE11.Win7.For.Windows.VirtualBox.zip -d /home/storystream/modernie_selenium/VMs/
  when: ie_version == 'ie11' and ie11_ova.stat.exists == False
  become: True
  become_user: storystream

#- name: Add cronjob to create IE8 VM
#  cron:
#    special_time=hourly
#    name="Delete and re-create modernie_selenium VM"
#    user="storystream"
#    job="/home/storystream/modernie_selenium/mkvm.sh /home/storystream/modernie_selenium/VMs/IE8\ -\Win7"
#  when: ie_version == 'ie8'
#  become: True
#  become_user: storystream
