---
- name: get modernie_selenium from Github
  git:
    repo=https://github.com/abjarnason/modernie_selenium.git
    dest=~/modernie_selenium
  become: True
  become_user: storystream

- name: get selenium-server-standalone-2.53.1.jar
  get_url:
    url=http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
    dest=~/modernie_selenium/Tools/selenium_conf
  become: True
  become_user: storystream

- name: get IEDriverServer_Win32_2.53.1.zip
  get_url:
    url=http://selenium-release.storage.googleapis.com/2.53/IEDriverServer_Win32_2.53.1.zip
    dest=~/modernie_selenium/Tools/selenium_conf/
  become: True
  become_user: storystream

- name: unzip IEDriverServer_Win32_2.53.1.zip
  command:
    unzip -o /home/storystream/modernie_selenium/Tools/selenium_conf/IEDriverServer_Win32_2.53.1.zip -d ~/modernie_selenium/Tools/selenium_conf/
  #unarchive:
  #  src=~/IEDriverServer_Win32_2.53.1.zip
  #  dest=~/modernie_selenium/Tools/selenium_conf/
  become: True
  become_user: storystream

- name: get deuac.iso
  get_url:
    url=https://github.com/tka/SeleniumBox/raw/master/deuac.iso
    dest=~/modernie_selenium/Tools/
  become: True
  become_user: storystream

- name: get jre-8u65-windows-i586.exe
  get_url:
    url=http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jre-8u65-windows-i586.exe
    dest=~/modernie_selenium/Tools/
    headers='Cookie:oraclelicense=accept-securebackup-cookie'
  become: True
  become_user: storystream

- name: Check if IE8 zip exists
  stat:
    path: ~/modernie_selenium/VMs/IE8.Win7.For.Windows.VirtualBox.zip
  register: ie8_zip_exists
  when: ie_version == 'ie8'
  become: True
  become_user: storystream

- name: Check if IE8 ova exists
  stat:
    path: ~/modernie_selenium/VMs/IE8\ -\ Win7.ova
  register: ie8_ova_exists
  when: ie_version == 'ie8'
  become: True
  become_user: storystream

- name: get IE8.Win7.For.Windows.VirtualBox.zip
  get_url:
    url=https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/IE8/Windows/IE8.Win7.For.Windows.VirtualBox.zip
    dest=~/modernie_selenium/VMs/
  when: ie_version == 'ie8' and ie8_zip_exists == False
  become: True
  become_user: storystream

- name: unzip IE8.Win7.For.Windows.VirtualBox.zip
  command: unzip -o /home/storystream/modernie_selenium/VMs/IE8.Win7.For.Windows.VirtualBox.zip -d /home/storystream/modernie_selenium/VMs/
  when: ie_version == 'ie8' and ie8_ova_exists == False
  become: True
  become_user: storystream

- name: Check if IE9 zip exists
  stat:
    path: ~/modernie_selenium/VMs/IE9.Win7.For.Windows.VirtualBox.zip
  register: ie9_zip_exists
  when: ie_version == 'ie9'
  become: True
  become_user: storystream

- name: Check if IE9 ova exists
  stat:
    path: ~/modernie_selenium/VMs/IE9\ -\ Win7.ova
  register: ie9_ova_exists
  when: ie_version == 'ie9'
  become: True
  become_user: storystream

- name: get IE9.Win7.For.Windows.VirtualBox.zip
  get_url:
    url=https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/IE9/Windows/IE9.Win7.For.Windows.VirtualBox.zip
    dest=~/modernie_selenium/VMs/
  when: ie_version == 'ie9' and ie9_zip_exists == False
  become: True
  become_user: storystream

- name: unzip IE9.Win7.For.Windows.VirtualBox.zip
  command: unzip -o /home/storystream/modernie_selenium/VMs/IE9.Win7.For.Windows.VirtualBox.zip -d /home/storystream/modernie_selenium/VMs/
  when: ie_version == 'ie9' and ie9_ova_exists == False
  become: True
  become_user: storystream

- name: Check if IE10 zip exists
  stat:
    path: ~/modernie_selenium/VMs/IE10.Win7.For.Windows.VirtualBox.zip
  register: ie10_zip_exists
  when: ie_version == 'ie10'
  become: True
  become_user: storystream

- name: Check if IE10 ova exists
  stat:
    path: ~/modernie_selenium/VMs/IE10\ -\ Win7.ova
  register: ie10_ova_exists
  when: ie_version == 'ie10'
  become: True
  become_user: storystream

- name: get IE10.Win7.For.Windows.VirtualBox.zip
  get_url:
    url=https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/IE10/Windows/IE10.Win7.For.Windows.VirtualBox.zip
    dest=~/modernie_selenium/VMs/
  when: ie_version == 'ie10' and ie10_zip_exists == False
  become: True
  become_user: storystream

- name: unzip IE10.Win7.For.Windows.VirtualBox.zip
  command: unzip -o /home/storystream/modernie_selenium/VMs/IE10.Win7.For.Windows.VirtualBox.zip -d /home/storystream/modernie_selenium/VMs/
  when: ie_version == 'ie10' and ie10_ova_exists == False
  become: True
  become_user: storystream

- name: Check if IE11 zip exists
  stat:
    path: ~/modernie_selenium/VMs/IE11.Win7.For.Windows.VirtualBox.zip
  register: ie11_zip_exists
  when: ie_version == 'ie11'
  become: True
  become_user: storystream

- name: Check if IE11 ova exists
  stat:
    path: ~/modernie_selenium/VMs/IE11\ -\ Win7.ova
  register: ie11_ova_exists
  when: ie_version == 'ie11'
  become: True
  become_user: storystream

- name: get IE11.Win7.For.Windows.VirtualBox.zip
  get_url:
    url=https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/IE11/Windows/IE11.Win7.For.Windows.VirtualBox.zip
    dest=~/modernie_selenium/VMs/
  when: ie_version == 'ie11' and ie11_zip_exists == False
  become: True
  become_user: storystream

- name: unzip IE11.Win7.For.Windows.VirtualBox.zip
  command: unzip -o /home/storystream/modernie_selenium/VMs/IE11.Win7.For.Windows.VirtualBox.zip -d /home/storystream/modernie_selenium/VMs/
  when: ie_version == 'ie11' and ie11_ova_exists == False
  become: True
  become_user: storystream
#- name: make user storystream the owner the modernie_selenium directory (and it's sub-directories)
#  command: chown storystream:storystream -R /home/storystream/modernie_selenium
#
#- name: run mkvm.sh script
#  command: /home/storystream/modernie_selenium/mkvm.sh /home/storystream/modernie_selenium/VMs/IE9\ -\ Win7.ova
#  become: yes
#  become_user: storystream
